# Generated by Django 4.2.4 on 2023-09-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='ava',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='user/'),
        ),
    ]
