# Generated by Django 4.2.4 on 2023-09-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_otp_vendor_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
