# Generated by Django 4.2.4 on 2023-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_vendor_ava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='ava',
            field=models.ImageField(blank=True, upload_to='user/'),
        ),
    ]
